ANCHO = 800
ALTURA = 600
TAM_PANTALLA = (ANCHO, ALTURA)
FPS = 60
SIZE_ICONO = (32, 32)

ALTURA_INICIAL = 0
ANCHO_INICIAL = 0
ANCHO_MEDIO = ANCHO // 2
ALTURA_MEDIO = ALTURA // 2
ANCHO_MAX = ANCHO
ALTURA_MAX = ALTURA


BOTTOM_LEFT = (ANCHO_INICIAL, ALTURA)
BOTTOM_MID = (ANCHO_MEDIO, ALTURA_MAX)
BOTTON_RIGHT = (ANCHO_MAX, ALTURA_MAX)
MID_LEFT = (ANCHO_INICIAL, ALTURA_MEDIO)
CENTRO = (ANCHO_MEDIO, ALTURA_MEDIO) 
MID_RIGHT = (ANCHO_MAX, ALTURA_MEDIO)
COORD_ORIGEN = (ANCHO_INICIAL,ALTURA_INICIAL)
TOP_MID = (ANCHO_MEDIO, ALTURA_INICIAL)
TOP_RIGHT = (ANCHO_MAX, ALTURA_INICIAL)

HOMER_TAM = (150, 200)
VELOCIDAD_HOMER = 14

DONA_TAM = (70, 70)
VELOCIDAD_DONA = 5

SCORE_POS = (50, 50)

RED = (255, 0, 0)
GREEN = (57, 255, 57)